# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'XMPP-Messenger-iOS' do
    pod 'xmpp-messenger-ios', :git => 'https://github.com/mrdavidrees/xmpp-messenger-ios.git', :branch => 'master'
end

